logging:
  level:
    net.ttddyy.dsproxy.listener: DEBUG

spring:
  application:
    name: ordering
  datasource:
    url: jdbc:h2:file:~/ordering;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  http:
    clients:
      imperative:
        factory: http_components
    serviceclient:
      product-catalog:
        base-url: http://localhost:8082
      rapidex:
        base-url: http://localhost:8081
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: false
    show-sql: false

algashop:
  integrations:
    shipping:
      provider: RAPIDEX