logging:
  level:
    net.ttddyy.dsproxy.listener: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://algashop-postgres:5432/ordering
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  http:
    clients:
      imperative:
        factory: http_components
    serviceclient:
      product-catalog:
        base-url: http://wiremock:8080
      rapidex:
        base-url: http://wiremock:8080

algashop:
  integrations:
    product-catalog:
      provider: PRODUCT_CATALOG
    shipping:
      provider: RAPIDEX