spring:
  datasource:
    url: ${DATASOURCE_JDBC_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  http:
    clients:
      imperative:
        factory: http_components
    serviceclient:
      product-catalog:
        base-url: ${PRODUCT_CATALOG_URL}
      rapidex:
        base-url: ${RAPIDEX_URL}

algashop:
  integrations:
    product-catalog:
      provider: PRODUCT_CATALOG
    shipping:
      provider: RAPIDEX